# Generated by Django 5.0.1 on 2024-01-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageproducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.URLField(default="https//"),
            preserve_default=False,
        ),
    ]
